In [2]:
import tensorflow as tf
import numpy as np

In [14]:
t = tf.constant([[1., 2., 3.], [4., 5., 6.]])
print("tensorflow: ", t, " => shape: ", t.shape)
print("numpy: ", t.numpy(), " => shape: ", t.numpy().shape)

tensorflow:  tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)  => shape:  (2, 3)
numpy:  [[1. 2. 3.]
 [4. 5. 6.]]  => shape:  (2, 3)


### 1 Index operation

In [20]:
print(t[:, 1:]) # get only 2 and 3 columns from matrix t

tf.Tensor(
[[2. 3.]
 [5. 6.]], shape=(2, 2), dtype=float32)


In [19]:
print(t[..., 1]) # column 2 only

tf.Tensor([2. 5.], shape=(2,), dtype=float32)


### 2 Tensor operations

In [21]:
print(t + 10)

tf.Tensor(
[[11. 12. 13.]
 [14. 15. 16.]], shape=(2, 3), dtype=float32)


In [22]:
print(t * 2)

tf.Tensor(
[[ 2.  4.  6.]
 [ 8. 10. 12.]], shape=(2, 3), dtype=float32)


In [23]:
print(t @ tf.transpose(t)) # matrix a multiply a.T

tf.Tensor(
[[14. 32.]
 [32. 77.]], shape=(2, 2), dtype=float32)


### 3 Numpy

In [32]:
print(t.numpy())  # convert tensorflow to numpy datatype

[[1. 2. 3.]
 [4. 5. 6.]]


In [31]:
print(np.square(t)) # use numpy to calculate tensorflow datatype

[[ 1.  4.  9.]
 [16. 25. 36.]]


In [33]:
np_t = np.array([1, 2, 3])
print(tf.constant(np_t))  # init a tensor object with numpy datatype

tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [4]:
print(tf.constant(3.14))

tf.Tensor(3.14, shape=(), dtype=float32)


### 4 Constant

In [7]:
t = tf.constant("tensorflow")

print(t)
print(tf.strings.length(t))

tf.Tensor(b'tensorflow', shape=(), dtype=string)
tf.Tensor(10, shape=(), dtype=int32)


In [15]:
t_array = tf.constant(["tensorflow", "keras", "pytorch"])
t_utf8 = tf.strings.unicode_decode(t_array, "utf8")
print(t_array)
print(t_utf8)

tf.Tensor([b'tensorflow' b'keras' b'pytorch'], shape=(3,), dtype=string)
<tf.RaggedTensor [[116, 101, 110, 115, 111, 114, 102, 108, 111, 119], [107, 101, 114, 97, 115], [112, 121, 116, 111, 114, 99, 104]]>
