In [2]:
import tensorflow as tf
import numpy as np

### Strings in Tensorflow constant

In [5]:
t = tf.constant("kaffee")
t

<tf.Tensor: id=3, shape=(), dtype=string, numpy=b'kaffee'>

In [7]:
print(tf.strings.length(t))
print(tf.strings.unicode_decode(t, "utf-8"))

tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor([107  97 102 102 101 101], shape=(6,), dtype=int32)


### RaggedTensor

In [13]:
r_ts1 = tf.ragged.constant([[11, 12], [11, 12, 13], [], [8]]) # tensor with 4 rows
r_ts2 = tf.ragged.constant([[1, 2], [], [8]]) # tensor with 3 rows
r_ts3 = tf.ragged.constant([[3, 4], [], [9]])
# concate two tensors -> append by rows
print(tf.concat([r_ts1, r_ts2], axis=0)) # tensor with 7 rows

# r_ts2 and r_ts3 have the same shape and can be concated by axis 1
print(tf.concat([r_ts2, r_ts3], axis=1))

<tf.RaggedTensor [[11, 12], [11, 12, 13], [], [8], [1, 2], [], [8]]>
<tf.RaggedTensor [[1, 2, 3, 4], [], [8, 9]]>


In [18]:
# links buendig
print(r_ts3.to_tensor()) # from [3, 4], [], [9] to [3, 4], [0, 0], [9, 0]

tf.Tensor(
[[3 4]
 [0 0]
 [9 0]], shape=(3, 2), dtype=int32)


### Sparse Tensor

In [23]:
s_ts = tf.SparseTensor(
    indices = [[0, 1], [1, 0], [2, 3]], # position for value
    values = [1, 2, 3], # value on position
    dense_shape = [3, 4] # tensor shape
)

In [27]:
print(tf.sparse.to_dense(s_ts))

tf.Tensor(
[[0 1 0 0]
 [2 0 0 0]
 [0 0 0 3]], shape=(3, 4), dtype=int32)


In [26]:
# normaly sparse tensor must be reorded to present data in right order
s_ts1 = tf.sparse.reorder(s_ts)
print(tf.sparse.to_dense(s_ts1))

tf.Tensor(
[[0 1 0 0]
 [2 0 0 0]
 [0 0 0 3]], shape=(3, 4), dtype=int32)
